# Generated by Django 3.2.5 on 2021-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Գրառման վերնագիր')),
                ('content', models.TextField(blank=True, verbose_name='Կոնտենտ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Հրապարակման ժամանակը')),
                ('edited_date', models.DateTimeField(auto_now=True, verbose_name='Խմբագրման ժամանակը')),
                ('is_published', models.BooleanField(default=True, verbose_name='Հրապարակված է')),
                ('image', models.ImageField(upload_to='media/contact/aboutus/', verbose_name='Լուսանկար')),
            ],
            options={
                'verbose_name': 'Գրառում ընկերության մասին',
                'verbose_name_plural': 'Գրառումներ ընկերության մասին',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Կապնվողի անունը')),
                ('email', models.EmailField(max_length=254, verbose_name='Կապնվողի էլ հասցեն')),
                ('message', models.TextField(verbose_name='Կապնվողի նամակը')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծվել է')),
            ],
            options={
                'verbose_name': 'Նամակ',
                'verbose_name_plural': 'Նամակներ',
                'ordering': ['-created_at'],
            },
        ),
    ]
